### ISSUE TITLE
NullPointerException in VerticalTextView.onDraw

### ISSUE THREAD

**Issue by VladimirWrites** [sockeqwe/SwipeBack#15]
Previous versions worked good but in last one I am getting big amount of crashes with this log:

```
Fatal Exception: java.lang.NullPointerException
       at com.hannesdorfmann.swipeback.view.VerticalTextView.onDraw(VerticalTextView.java:54)
       at android.view.View.draw(View.java:15278)
       at android.view.View.getDisplayList(View.java:14172)
       at android.view.View.getDisplayList(View.java:14214)
       at android.view.View.draw(View.java:14992)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
       at android.view.View.draw(View.java:15281)
       at android.view.View.getDisplayList(View.java:14172)
       at android.view.View.getDisplayList(View.java:14214)
       at android.view.View.draw(View.java:14992)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
       at com.hannesdorfmann.swipeback.BuildLayerFrameLayout.dispatchDraw(BuildLayerFrameLayout.java:83)
       at android.view.View.draw(View.java:15281)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:14172)
       at android.view.View.getHardwareLayerDisplayList(View.java:14199)
       at android.view.View.getHardwareLayer(View.java:13925)
       at android.view.View.buildLayer(View.java:13853)
       at com.hannesdorfmann.swipeback.BuildLayerFrameLayout$2.run(BuildLayerFrameLayout.java:95)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5694)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by sockeqwe** [comment]
can you debug / reproduce it somehow?
Seems that `getLayout()` return null for some strange reason? Do you display any text?

**Comment by vlad1m1r990** [comment]
I am displaying "Back" text translated to few languages. I can't reproduce bug but I am getting reports on Crashlytics. All devices are Samsung :D.
